INSERT INTO api_clients_app.api_clients (
  client_id,
  client_type,
  status,
  environment,
  rate_limit_profile,
  min_app_version,
  max_app_version,
  display_name,
  description,
  platform,
  surface,
  allowed_audiences,
  allowed_origins,
  ip_allowlist,
  require_mtls,
  is_version_enforced,
  user_rate_policy,
  client_safety_policy,
  notes,
  updated_at
)
VALUES
  (
    'wildon-control-web',
    'public',
    'active',
    'prod',
    'control_v1',
    '',
    '',
    'Wildon Control Web',
    'First-party control dashboard web client',
    'web',
    'control',
    ARRAY['control'],
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    FALSE,
    FALSE,
    'user_control_v1',
    'client_control_medium',
    'migration upsert',
    NOW()
  ),
  (
    'wildon-control-dashboard-prod',
    'public',
    'active',
    'prod',
    'control_v1',
    '',
    '',
    'Wildon Control Dashboard Production',
    'First-party control dashboard web client (prod)',
    'web',
    'control',
    ARRAY['control'],
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    FALSE,
    FALSE,
    'user_control_v1',
    'client_control_medium',
    'migration upsert',
    NOW()
  ),
  (
    'wildon-control-dashboard-dev',
    'public',
    'active',
    'dev',
    'control_v1',
    '',
    '',
    'Wildon Control Dashboard Development',
    'First-party control dashboard web client (dev)',
    'web',
    'control',
    ARRAY['control'],
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    FALSE,
    FALSE,
    'user_control_v1',
    'client_control_medium',
    'migration upsert',
    NOW()
  )
ON CONFLICT (client_id) DO UPDATE
SET
  client_type = EXCLUDED.client_type,
  status = EXCLUDED.status,
  environment = EXCLUDED.environment,
  rate_limit_profile = EXCLUDED.rate_limit_profile,
  min_app_version = EXCLUDED.min_app_version,
  max_app_version = EXCLUDED.max_app_version,
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  platform = EXCLUDED.platform,
  surface = EXCLUDED.surface,
  allowed_audiences = EXCLUDED.allowed_audiences,
  allowed_origins = EXCLUDED.allowed_origins,
  ip_allowlist = EXCLUDED.ip_allowlist,
  require_mtls = EXCLUDED.require_mtls,
  is_version_enforced = EXCLUDED.is_version_enforced,
  user_rate_policy = EXCLUDED.user_rate_policy,
  client_safety_policy = EXCLUDED.client_safety_policy,
  notes = EXCLUDED.notes,
  updated_at = NOW();
