-- Seed API clients for public (mobile app) and platform (partner dashboard) surfaces.

INSERT INTO api_clients_app.api_clients (
  client_id,
  client_type,
  status,
  environment,
  rate_limit_profile,
  min_app_version,
  max_app_version,
  display_name,
  description,
  platform,
  surface,
  allowed_audiences,
  allowed_origins,
  ip_allowlist,
  require_mtls,
  is_version_enforced,
  user_rate_policy,
  client_safety_policy,
  notes,
  updated_at
)
VALUES
  -- Public surface: Mobile app (Android)
  (
    'wildon-mobile-android',
    'public',
    'active',
    'prod',
    'public_v1',
    '',
    '',
    'Wildon Mobile Android',
    'First-party Android mobile app',
    'android',
    'public',
    ARRAY['public'],
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    FALSE,
    FALSE,
    'user_public_v1',
    'client_public_standard',
    'migration seed',
    NOW()
  ),
  -- Public surface: Mobile app (iOS)
  (
    'wildon-mobile-ios',
    'public',
    'active',
    'prod',
    'public_v1',
    '',
    '',
    'Wildon Mobile iOS',
    'First-party iOS mobile app',
    'ios',
    'public',
    ARRAY['public'],
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    FALSE,
    FALSE,
    'user_public_v1',
    'client_public_standard',
    'migration seed',
    NOW()
  ),
  -- Public surface: Dev/testing (any platform)
  (
    'wildon-mobile-dev',
    'public',
    'active',
    'dev',
    'public_v1',
    '',
    '',
    'Wildon Mobile Dev',
    'Development/testing client for public surface',
    'any',
    'public',
    ARRAY['public'],
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    FALSE,
    FALSE,
    'user_public_v1',
    'client_public_standard',
    'migration seed',
    NOW()
  ),
  -- Platform surface: Partner web dashboard
  (
    'wildon-platform-web',
    'public',
    'active',
    'prod',
    'platform_v1',
    '',
    '',
    'Wildon Platform Web',
    'First-party partner dashboard web client',
    'web',
    'platform',
    ARRAY['platform'],
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    FALSE,
    FALSE,
    'user_platform_v1',
    'client_platform_medium',
    'migration seed',
    NOW()
  ),
  -- Platform surface: Dev/testing
  (
    'wildon-platform-dev',
    'public',
    'active',
    'dev',
    'platform_v1',
    '',
    '',
    'Wildon Platform Dev',
    'Development/testing client for platform surface',
    'any',
    'platform',
    ARRAY['platform'],
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    FALSE,
    FALSE,
    'user_platform_v1',
    'client_platform_medium',
    'migration seed',
    NOW()
  )
ON CONFLICT (client_id) DO UPDATE
SET
  client_type = EXCLUDED.client_type,
  status = EXCLUDED.status,
  environment = EXCLUDED.environment,
  rate_limit_profile = EXCLUDED.rate_limit_profile,
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  platform = EXCLUDED.platform,
  surface = EXCLUDED.surface,
  allowed_audiences = EXCLUDED.allowed_audiences,
  user_rate_policy = EXCLUDED.user_rate_policy,
  client_safety_policy = EXCLUDED.client_safety_policy,
  notes = EXCLUDED.notes,
  updated_at = NOW();
